import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import User from '../components/User'
import {
    createStyles,
    Grid,
    makeStyles,
    Theme,
    Typography,
} from '@material-ui/core'

const useStyles = makeStyles((theme: Theme) =>
    createStyles({
        root: {
            textAlign: 'center',
            minHeight: '100vh',
        },
        small: {
            width: theme.spacing(3),
            height: theme.spacing(3),
        },
        large: {
            margin: '0 auto 20px',
            width: theme.spacing(10),
            height: theme.spacing(10),
        },
        title: {
            textAlign: 'left',
        },
        content: {
            marginBottom: '20px',
        },
    })
)
export default function Home() {
    const classes = useStyles()
    return (
        <div className={classes.root}>
            <Head>
                <title>Swistory</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <Grid container justify="center" className={classes.content}>
                <Grid item xs={12} md={8}>
                    <User />
                </Grid>
            </Grid>
            <Grid container justify="center" className={classes.content}>
                <Grid item xs={12} md={8}>
                    <Typography variant="h3" className={classes.title}>
                        Recent Your Training
                    </Typography>
                </Grid>
            </Grid>
            <Grid container justify="center" className={classes.content}>
                <Grid item xs={12} md={8}>
                    <Typography variant="h3" className={classes.title}>
                        Other Training Menu
                    </Typography>
                </Grid>
            </Grid>
        </div>
    )
}
