import { useQuery } from '@apollo/client'
import {
  createStyles,
  Grid,
  List,
  ListItem,
  makeStyles,
  Theme,
  Typography,
} from '@material-ui/core'
import gql from 'graphql-tag'
import Head from 'next/head'
import User from 'components/User'
import { MenuHeading } from 'components/Menu'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      textAlign: 'center',
      minHeight: '100vh',
    },
    small: {
      width: theme.spacing(3),
      height: theme.spacing(3),
    },
    large: {
      margin: '0 auto 20px',
      width: theme.spacing(10),
      height: theme.spacing(10),
    },
    title: {
      textAlign: 'left',
    },
    content: {
      marginBottom: '20px',
    },
  })
)

const LIST_MENU = gql`
  {
    menus {
      id
      level
      aim
      description
      createdAt
      group {
        id
        name
      }
    }
  }
`
type Menu = {
  id: number
  level: string
  aim: string
  description: string
}

export default function Home() {
  const classes = useStyles()
  const { loading, error, data } = useQuery(LIST_MENU)

  if (!data || loading) return <p>Loading...</p>

  const menus: Menu[] = data.menus

  return (
    <div className={classes.root}>
      <Head>
        <title>Swistory</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Grid container justify="center" className={classes.content}>
        <Grid item xs={12} md={8}>
          <User />
        </Grid>
      </Grid>
      <Grid container justify="center" className={classes.content}>
        <Grid item xs={12} md={8}>
          <List>
            {menus.map((menu) => (
              <ListItem>
                <MenuHeading menu={menu} />
              </ListItem>
            ))}
          </List>
        </Grid>
      </Grid>
    </div>
  )
}
